name: reviseitai
description: "AI-powered spaced repetition and active recall learning app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-228.0.dev

dependencies:
  flutter:
    sdk: flutter
  # UI and animations
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  flutter_animate: ^4.5.0
  liquid_swipe: ^3.1.0
  glassmorphism: ^3.0.0
  flutter_riverpod: ^2.4.9
  rive: ^0.12.4
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  # API and data handling
  http: ^1.1.2
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Mind map visualization
  graphview: ^1.2.0
  
  # PDF handling
  flutter_pdfview: ^1.3.2
  file_picker: ^10.2.0
  
  # Calendar integration
  table_calendar: ^3.0.9
  
  # Additional dependencies
  google_sign_in: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon.png
    - assets/animations/learning.json
    - assets/animations/
    
